#!/bin/bash
#SBATCH --job-name=cellrangerCount_female07                           # Job name
#SBATCH --nodes=1                                       # Numbers of nodes
#SBATCH --ntasks=8                                      # Number of CPU (tasks)
#SBATCH --time=18:00:00                                 # Time limit hrs:min:sec
#SBATCH --partition=short                               # Partition/queue requested on server    
#SBATCH --mem=64gb                                       # Memory limit
#SBATCH --output=/scratch/Shares/dowell/temp/ChrisO/SR2024/eando/cellrangercount.%j.out
#SBATCH --error=/scratch/Shares/dowell/temp/ChrisO/SR2024/eando/cellrangercount.%j.err


##########################################################################################
################## MODULE LOAD ###################################################

module load cellranger/7.2.0

##########################################################################################
################## DISPLAY JOB CONTEXT ###################################################

echo Job: $SLURM_JOB_NAME with ID $SLURM_JOB_ID
echo Running on host `hostname`
echo Using $SLURM_NTASKS processors across $SLURM_NNODES nodes

##########################################################################################
################## RUN JOB ###############################################################


cellranger count --id=T21BM_male19 \
 --fastqs=/scratch/Shares/dowell/temp/ChrisO/SR2024/fastq/sampled \
 --transcriptome=/scratch/Shares/dowell/temp/ChrisO/SR2024/refdata-gex-GRCh38-2020-A \
 --sample=DSOX19_1 \
 --include-introns=true \
 --localcores=8    ###must match ntasks above

                                                                                
echo Job finished at `date +"%T %a %d %b %Y"`
